Added manager notifications
Claromentis/cla-thankyou pull request #27
Opened 2019-03-25 12:55 UTC by andy-ce-taylor

Change request:
https://discover.claromentis.com/forms/changes/view/022837#_form

Automatic Thank you notifications to Supervisors.

Core has a branch called CB_notifs which should be merged at the same time:
https://git.claromentis.net/core/web/merge_requests/368

### Prototype
http://prototypes.claromentis.net/Thank%20you%20-%20line%20manager%20notifications/#id=jg3v03&p=home&g=1

### Checklist
Criteria that must be met before merging. Check these as they are completed.

- [ ] Code reviewed
- [ ] QA tested
- [ ] Change log updated

2019-03-25 16:40 UTC, hexus requested changes
- `DBVar` to `Config` change is needed (see my comment on that file)
- Porting your IM config changes from Core into the `Plugin` class using the `GetIMConfig()` method, as discussed

Looks fab otherwise!

2019-03-25 16:40 UTC, hexus commented on classes/SettingsRepository.php
> +}
Can this instead be changed to use `Claromentis\Core\Config\Config` interface? It's best not to use `DBVar` for config.

In fact, instead of introducing this repository you could solely just add a config service in `Plugin`, and use that in place of this repo.

i.e:

```php
$app['thankyou.config'] = function ($app) {
	return $app['config.factory']('thankyou');
};
```

You can then easily consume the `thankyou.config` service to get and set variables, adhering to the `Claromentis\Core\Config\WritableConfig` interface.

```php
/**
 * @var \Claromentis\Core\Config\WritableConfig
 */
$config = $app['thankyou.config'];

$value = $config->Get('config_variable_name');

$config->Set('config_variable_name', $new_value);
```

2019-03-26 13:09 UTC, hexus requested changes
Looks great, just need xSettingsRepository to be removed :+1:

2019-03-26 13:53 UTC, andy-ce-taylor commented
The suggestions from Chris have been implemented - Ready for testing

2019-03-26 14:42 UTC, hexus commented
For some reason, the commit in which you removed the old file isn't showing up in this PR. Strange.

2019-03-26 15:21 UTC, hexus approved these changes

2019-03-27 16:22 UTC, olganovosad commented
Hello,

tested this in win83, linux83, win87, linux87 in ie11, safari, chrome, firefox.

Tested line manager notifications On and Off
Tested multiple users with different managers
tested multiple users with same manager
Tested all communication settings for line manager and user who being thanked
Tested admin access to notification section logged in under usual user
Tested line managers and users in direct report (only line managers receive notification)
Tested with no manager when the check box is ticked

The only left is daily digest which will be received tomorrow.

Issues reported with branch prefix in the summary and assigned to Andy.

2019-03-27 18:39 UTC, hexus requested changes

2019-03-27 18:39 UTC, hexus commented on classes/LineManagerNotifier.php
> +class LineManagerNotifier extends ErrorHandler
Just realised that this extends `ErrorHandler`. Does it need to? I'd recommend avoiding this pattern.

2019-03-27 18:39 UTC, hexus commented on classes/LineManagerNotifier.php
> +			NotificationMessage::Send('thankyou.new_thanks_manager', $params, [$line_manager], Constants::IM_TYPE_THANKYOU, null, $thanker_id);
#33 Currently sending per-recipient instead of per line manager

2019-03-28 15:16 UTC, hexus commented on classes/LineManagerNotifier.php
> +class LineManagerNotifier extends ErrorHandler
This has been resolved, cheers

2019-03-28 15:16 UTC, hexus commented on classes/LineManagerNotifier.php
> +			NotificationMessage::Send('thankyou.new_thanks_manager', $params, [$line_manager], Constants::IM_TYPE_THANKYOU, null, $thanker_id);
Fabulous 🎉

2019-03-28 16:23 UTC, hexus approved these changes

2019-03-28 16:23 UTC, merged